### ISSUE TITLE
Could not get it strated a lot of erros.

### ISSUE THREAD

**Issue by evghenitirulnic** [RobWunderlich/qcb-qlik-sse#1]
During first start i get errors. There is no server.js 

PS C:\Dev\qcb-qlik-sse> npm start

> qcb-qlik-sse@0.2.0 start C:\Dev\qcb-qlik-sse
> node index.js

C:\Dev\qcb-qlik-sse\node_modules\grpc\src\grpc_extension.js:57
    throw e;
    ^

Error: Cannot find module 'C:\Dev\qcb-qlik-sse\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node'
Require stack:
- C:\Dev\qcb-qlik-sse\node_modules\grpc\src\grpc_extension.js
- C:\Dev\qcb-qlik-sse\node_modules\grpc\src\client_interceptors.js
- C:\Dev\qcb-qlik-sse\node_modules\grpc\src\client.js
- C:\Dev\qcb-qlik-sse\node_modules\grpc\index.js
- C:\Dev\qcb-qlik-sse\node_modules\qlik-sse\lib\index.js
- C:\Dev\qcb-qlik-sse\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Dev\qcb-qlik-sse\node_modules\grpc\src\grpc_extension.js:32:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Dev\\qcb-qlik-sse\\node_modules\\grpc\\src\\grpc_extension.js',
    'C:\\Dev\\qcb-qlik-sse\\node_modules\\grpc\\src\\client_interceptors.js',
    'C:\\Dev\\qcb-qlik-sse\\node_modules\\grpc\\src\\client.js',
    'C:\\Dev\\qcb-qlik-sse\\node_modules\\grpc\\index.js',
    'C:\\Dev\\qcb-qlik-sse\\node_modules\\qlik-sse\\lib\\index.js',
    'C:\\Dev\\qcb-qlik-sse\\index.js'
  ]
}

**Comment by RobWunderlich** [comment]
Did you do npm install? Was it successful?

**Comment by evghenitirulnic** [comment]
Yeap with NPM 

 

 

I’ve managhed to make it running

 

But problem is that, in package json the reference is to server.js but it is not there anymore , instead you have index.js
